"""Consensus Analysis cho 9 mô hình hiện tại.

Tầng này đọc kết quả của 9 mô hình như 9 góc nhìn độc lập, xác định các nhóm
đồng thuận, mâu thuẫn và trung tính, đo mức độ thông tin chung bằng correlation,
rồi mô tả lại bằng Market Narrative. Tầng này không tạo Composite Score.
"""

from .narrative import build_narrative
from .overlap import (
    DEFAULT_OVERLAP_THRESHOLD,
    OverlapReport,
    analyze_overlap,
    available_score_columns,
    information_clusters,
    overlap_pairs,
    score_correlation,
)
from .perspectives import (
    CONTEXT,
    DIRECTIONAL,
    NEGATIVE,
    NEUTRAL,
    PERSPECTIVES,
    PERSPECTIVES_BY_KEY,
    POSITIVE,
    RISK,
    ROLE_LABELS,
    ROLE_ORDER,
    SCORE_KEYS,
    TONE_CALM,
    TONE_DOWN,
    TONE_FLAT,
    TONE_INFO,
    TONE_NA,
    TONE_UP,
    TONE_WARN,
    UNAVAILABLE,
    Perspective,
    perspectives_for_role,
    stance_tone,
    strength_label,
)
from .report import (
    CONSENSUS_LABELS,
    ConflictNote,
    ConsensusGroup,
    SymbolConsensus,
    ViewStance,
    analyze_symbol,
    consensus_overview,
    consensus_report,
    views_table,
)

__all__ = [
    "PERSPECTIVES",
    "PERSPECTIVES_BY_KEY",
    "SCORE_KEYS",
    "Perspective",
    "perspectives_for_role",
    "stance_tone",
    "strength_label",
    "TONE_UP",
    "TONE_DOWN",
    "TONE_WARN",
    "TONE_CALM",
    "TONE_INFO",
    "TONE_FLAT",
    "TONE_NA",
    "DIRECTIONAL",
    "CONTEXT",
    "RISK",
    "ROLE_LABELS",
    "ROLE_ORDER",
    "POSITIVE",
    "NEUTRAL",
    "NEGATIVE",
    "UNAVAILABLE",
    "DEFAULT_OVERLAP_THRESHOLD",
    "OverlapReport",
    "analyze_overlap",
    "available_score_columns",
    "score_correlation",
    "overlap_pairs",
    "information_clusters",
    "build_narrative",
    "CONSENSUS_LABELS",
    "ConflictNote",
    "ConsensusGroup",
    "SymbolConsensus",
    "ViewStance",
    "analyze_symbol",
    "consensus_report",
    "consensus_overview",
    "views_table",
]
